### ISSUE TITLE
TemplePlusConfig.exe encounters Windows API Code Pack exception during setup

### ISSUE THREAD

**Issue by lucianposton** [GrognardsFromHell/TemplePlus#257]
TemplePlusConfig.exe fails during setup with the following exception. It looks like Temple+ uses Windows API Code Pack which is no longer even supported by microsoft and fails here with a System.NotImplementedException.

```
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'TemplePlusConfig.MainWindow' that matches the specified binding constraints threw an exception. ---> System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.WindowsAPICodePack.Shell.IKnownFolderNative.GetRedirectionCapabilities()
   at Microsoft.WindowsAPICodePack.Shell.KnownFolderSettings.GetFolderProperties(IKnownFolderNative knownFolderNative)
   at Microsoft.WindowsAPICodePack.Shell.FileSystemKnownFolder.get_KnownFolderSettings()
   at Microsoft.WindowsAPICodePack.Shell.FileSystemKnownFolder.get_Path()
   at TemplePlusConfig.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TemplePlusConfig.App.Main()
   at TemplePlusConfig.Program.Main(String[] args)
```

**Comment by lucianposton** [comment]
The specific stack trace above occurs with any winapi implementation where [IKnownFolder::GetRedirectionCapabilities](https://msdn.microsoft.com/en-us/library/windows/desktop/bb761764(v=vs.85).aspx) returns E_NOTIMPL, e.g. wine in my case.

I'll submit a patch to wine to stub out this winapi implementation later, fyi in case this project plans to continue using the deprecated Windows API Code Pack in the same manner it does currently. That'll fix it on wine if that platform is the only concern.

**Comment by shartte** [comment]
This is independent of the codepack, really. We just don't have a fallback
for the savegame folder, I'd guess. I am surprised wine doesn't
Implement this. Other games are using that folder as well.
We might use some other folder as fallback hmmm...

**Comment by lucianposton** [comment]
Wine has the saved games folder. Using the known folder itself is fine. Wine doesn't implement the folder redirection capabilities however. I'm not sure why Windows API Code Pack finds it necessary to check the saved games folder for folder redirection capabilities. It's a win8+ feature that's something like symlinking to a network filesystem.

**Comment by shartte** [comment]
The feature is actually in Vista, at least the API in question is available since Vista.
Fun fact: Wine actually does implement the redirection apparently: https://source.winehq.org/git/wine.git/blob/6864803f1ab70f9f9e90903b13e67da40973d12a:/dlls/shell32/shellpath.c#l5146

Although the function to query whether redirection is allowed is unimplemented, heh :)

**Comment by shartte** [comment]
I've committed a fix that uses an alternative API that Wine should fully implement.

**Comment by shartte** [comment]
You can grab "nightly" builds of that here:

https://ci.appveyor.com/project/shartte/templeplus/build/0.1.0-pre+1494/artifacts

**Comment by lucianposton** [comment]
Thanks for the fix. I'll test out your change once I get wine working with the dx11 apis temple+ requires.
